from . import food_consultation_ingredient
from . import food_consultation_preparation
from . import food_consultation_detail
from . import food_conslutation_menu
from . import food_consultation_flavor
from . import food_consultation_benefit
from . import food_consultation_image
from . import food_consultation_dessert
from . import food_consultation_season
from . import food_intro_web